name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      sapphire-localnet-ci:
        image: ghcr.io/oasisprotocol/sapphire-localnet:latest
        ports:
          - 8545:8545
          - 8546:8546
        env:
          OASIS_DEPOSIT_BINARY: /oasis-deposit -test-mnemonic -n 5
        options: >-
          --rm
          --health-cmd="test -f /CONTAINER_READY"
          --health-start-period=90s
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: https://github.com/oasisprotocol/sapphire-paratime.git
        path: /wrapper/

    - name: Build sapphirepy .whl file
      working-directory: /wrapper/sapphire-paratime/clients/py
      run: |
        pip3 install --user -r requirements.txt
        pip3 install --user -r requirements.dev.txt
        make
      

    - name: Install sapphirepy .whl file
      run: |
        pip3 install --user /wrapper/sapphire-paratime/clients/py/dist/sapphirepy-0.1.0-py3-none-any.whl
        pip3 install --user -r requirements.txt

    - name: Lint code
      run: |
        pip install flake8
        flake scripts/
        flake main.py
        flake cli_app.py

    - name: Run tests
      run: |
        pytest tests/
